version: '3.3'

services:
  docker-mysql:
    container_name: docker-mysql
    image: mysql:8.0.27
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: victim
      MYSQL_PASSWORD: password1
      MYSQL_DATABASE: my_db
    ports:
        - "3306:3306"
